binaries:
  - ruby-2.3.7
  - ruby-2.4.4
  - ruby-2.5.1
distributions:
  centos-7: hoot/centos7-minimal
  ubuntu_14.04-64: hoot/trusty-minimal
  ubuntu_16.04-64: ubuntu/xenial64
releases:
  centos: http://en.wikipedia.org/wiki/CentOS#CentOS_releases
  debian: http://www.debian.org/releases/
  fedora: https://fedoraproject.org/wiki/Releases
  opensuse: http://en.opensuse.org/Lifetime
  ubuntu: https://wiki.ubuntu.com/Releases
image_links:
  - https://app.vagrantup.com
  - https://rvm_io.global.ssl.fastly.net/vboxes/
  - http://www.vagrantbox.es
